/* DO NOT EDIT THIS FILE - it is machine generated */
#include "C_preprocess.hpp"
#include "../../../../../Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_example_imageprocessing_CaptureImage_ImageSave */

#ifndef _Included_com_example_imageprocessing_CaptureImage_ImageSave
#define _Included_com_example_imageprocessing_CaptureImage_ImageSave
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imageprocessing_CaptureImage_ImageSave
 * Method:    getvalue
 * Signature: (J)I
 */
extern "C" JNIEXPORT jint JNICALL Java_com_example_imageprocessing_CaptureImage_00024ImageSave_getvalue
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
